### ISSUE TITLE
Sometimes I can't Open Web Page

### ISSUE THREAD

**Issue by Lydocan** [artificerpi/gofsnet#1]
Sometimes I try to open a page by using this client, it will fail and turn to [http://202.38.193.65/] this page. I don't know why, cause I don't have some test tools. By the way, I use win10 system. When I meet this trouble, I can try more times, and it can open the right page, but I think it might be a bug..

**Comment by qtopie** [comment]
Thanks for reporting this issue. Have you try to click the `reload` option when you are disconnected?

**Comment by Lydocan** [comment]
Next time I will have a try, but sometimes the program doesn’t exist, I guess it may have some problem and be killed.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kev<mailto:notifications@github.com>
发送时间: 2017年4月3日 22:44
收件人: artificerpi/gofsnet<mailto:gofsnet@noreply.github.com>
抄送: Lydocan<mailto:lydocan@gmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [artificerpi/gofsnet] Sometimes I can't Open Web Page (#1)


Thanks for reporting this issue. Have you try to click the reload option when you are disconnected?

**Comment by Lydocan** [comment]
I try to `reload`, it's useful. So, would you mind add a function to auto reload when program find it can't connect to the internet? Just a suggestion, thank you.

**Comment by qtopie** [comment]
Glad to hear it's working. In fact, the cli version has been added this
function, and the gui version will add it soon, too.  Maybe the color of
the tray icon should be changed to indicate the status of network when it's
disconnected from network.

Lydocan <notifications@github.com>于2017年4月4日周二 10:35写道：

I try to reload, it's useful. So, would you mind add a function to auto
reload when program find it can't connect to the internet? Just a
suggestion, thank you.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/artificerpi/gofsnet/issues/1#issuecomment-291377741>,
or mute the thread

**Comment by qtopie** [comment]
Hi! @Lydocan I have merged codes from master branch, see the commit [895aa34](https://github.com/artificerpi/gofsnet/commit/895aa3415d103705d17987bb3fe2ac2723147717 "merge from master")

**Comment by qtopie** [comment]
fix bugs in commit https://github.com/artificerpi/gofsnet/commit/e5344df11039a201b19c394c5660f5203a48ed3b
